name: Build MathePropriete for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Installer Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # 4. Installer PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 5. Construire le projet avec PyInstaller
      - name: Build with PyInstaller
        run: |
         pyinstaller --onefile --icon=mathepropriete.ico mathepropriete.py


      # 6. Archiver le build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mathepropriete-macos
          path: dist/mathepropriete
